name: test

on: push

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: date
  job2:
    name: Second Job
    runs-on: winod
    steps:
      - name: Step one
        run: get-date
  job3:
    name: Third Job
    runs-on: macos-latest
    steps:
      - name: Step one
        run: date
  job4:
    name: Fourth Job
    runs-on: ubuntu-18.04
    needs: [job1, job2, job3]
    steps:
      - name: Step one
        run: date
